global_defs {
    router_id SYS-ATL-DB02
}

vrrp_script haproxy {
    script "killall -0 haproxy"
    interval 2
    weight 2
}

vrrp_instance ADMIN {
    virtual_router_id 50
    advert_int 2
    priority 101
    state MASTER
    interface ens192
    virtual_ipaddress {
        192.168.11.128/24
    }
    track_script {
        haproxy
    }
}